app/urls.py
from django.urls import path

from app.views import HomeView


urlpatterns = [
    path(route='', view=HomeView.as_view(), name='app_home'),
]

app_config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include
from django.urls import path


urlpatterns = [
    path(route='', view=include('app.urls')),
    path(route='projects/', view=include('projects.urls')),
    path(route='accounts/', view=include('authentication.urls')),
    path(route='admin/', view=admin.site.urls),
]


# Required for debugging the SQL queries.
if getattr(settings, 'DEBUG', False):
    import debug_toolbar
    urlpatterns.insert(0, path(route='__debug__/', view=include(debug_toolbar.urls)))

projects/urls.py
from django.urls import include
from django.urls import path

from projects.views import ProjectCreateView
from projects.views import ProjectDeleteView
from projects.views import ProjectDetailView
from projects.views import ProjectListView
from projects.views import ProjectUpdateView


urlpatterns = [
    path(route='', view=ProjectListView.as_view(), name='project_list'),
    path(route='create/', view=ProjectCreateView.as_view(), name='project_create'),
    path(route='<int:project_pk>/', view=ProjectDetailView.as_view(), name='project_detail'),
    path(route='<int:project_pk>/sections/', view=include('sections.urls')),
    path(route='<int:project_pk>/update/', view=ProjectUpdateView.as_view(), name='project_update'),
    path(route='<int:project_pk>/delete/', view=ProjectDeleteView.as_view(), name='project_delete'),
]

projects/models.py
from django.db import models

from authentication.models import User


class Project(models.Model):
    title = models.CharField(
        blank=False,
        null=False,
        verbose_name='Title',
    )
    owner = models.ForeignKey(
        blank=False,
        null=False,
        to=User,
        on_delete=models.CASCADE,
        related_name='owner_of_projects',
        verbose_name='Owner',
    )
    members = models.ManyToManyField(
        blank=True,
        to=User,
        related_name='member_of_projects',
        verbose_name='Members',
    )

    def __str__(self) -> str:
        return self.title

sections/models.py
from django.db import models

from projects.models import Project


class Section(models.Model):
    name = models.CharField(
        blank=False,
        null=False,
        verbose_name='Name',
    )
    project = models.ForeignKey(
        blank=False,
        null=False,
        to=Project,
        on_delete=models.CASCADE,
        related_name='sections',
        verbose_name='Project',
    )

    def __str__(self) -> str:
        return self.name

projects/forms.py
from django import forms

from projects.models import Project


class ProjectCreateForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = (
            'title',
            'members',
        )
        widgets = {
            'members': forms.CheckboxSelectMultiple,
        }


class ProjectUpdateForm(ProjectCreateForm):
    pass

projects/views.py
from typing import Any
from typing import cast

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.db.models.query import QuerySet
from django.forms import BaseModelForm
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import UpdateView

from authentication.models import User
from projects.forms import ProjectCreateForm
from projects.forms import ProjectUpdateForm
from projects.models import Project


class ProjectViewMixin(LoginRequiredMixin, View):
    model = Project
    pk_url_kwarg = 'project_pk'

    def get_queryset(self) -> QuerySet[Project]:
        queryset = self.model.objects.all()
        queryset = queryset.select_related('owner')
        queryset = queryset.prefetch_related('members', 'sections')
        queryset = queryset.distinct()
        user = self.request.user

        if isinstance(self, (ProjectListView, ProjectDetailView)):
            filters = Q(owner=user) | Q(members=user)
        elif isinstance(self, (ProjectUpdateView, ProjectDeleteView)):
            filters = Q(owner=user)
        else:
            raise Exception()

        if user.is_superuser:
            return queryset
        else:
            return queryset.filter(filters)


class ProjectListView(ProjectViewMixin, ListView):
    """User can get the list of projects where he is a member or owner, if user is superuser he can get all projects."""
    context_object_name = 'projects'
    template_name = 'projects/list.html'
    extra_context = {'page_title': 'Projects'}

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        user = self.request.user
        projects = cast(list[Project], self.object_list)  # pyright: ignore[reportAttributeAccessIssue]
        context['projects'] = dict()

        # user is owner;
        context['projects']['my'] = filter(lambda p: user == p.owner, projects)
        # user is member and not owner;
        context['projects']['member'] = filter(lambda p: user in p.members.all() and not p.owner == user, projects)

        if not user.is_superuser:
            return context

        # user is not member and is not owner;
        context['projects']['admin_list'] = filter(lambda p: user != p.owner and user not in p.members.all(), projects)

        return context


class ProjectCreateView(ProjectViewMixin, CreateView):
    """User can create new project if he is logged in."""
    form_class = ProjectCreateForm
    template_name = 'projects/create.html'

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        project = cast(Project, form.instance)
        user = cast(User, self.request.user)
        project.owner = user
        return super().form_valid(form)

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Create project'
        return context

    def get_success_url(self) -> str:
        project = cast(Project, self.object)  # pyright: ignore[reportAttributeAccessIssue]
        return reverse_lazy('project_detail', kwargs={self.pk_url_kwarg: project.pk})


class ProjectDetailView(ProjectViewMixin, DetailView):
    """User can get the detail of the project only if he is a owner or member of project or superuser."""
    context_object_name = 'project'
    template_name = 'projects/detail.html'

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        user = self.request.user
        project = cast(Project, self.object)  # pyright: ignore[reportAttributeAccessIssue]
        context = super().get_context_data(**kwargs)
        context['page_title'] = f'Detail of project: {project.title}'
        context['user_is_admin'] = user.is_superuser
        context['user_is_project_owner'] = project.owner == user
        return context


class ProjectUpdateView(ProjectViewMixin, UpdateView):
    """User can update the project only if he is a owner of project or superuser."""
    form_class = ProjectUpdateForm
    context_object_name = 'project'
    template_name = 'projects/update.html'

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        project = cast(Project, self.object)  # pyright: ignore[reportAttributeAccessIssue]
        context = super().get_context_data(**kwargs)
        context['page_title'] = f'Update project: {project.title}'
        return context

    def get_success_url(self) -> str:
        project = cast(Project, self.object)  # pyright: ignore[reportAttributeAccessIssue]
        return reverse_lazy('project_detail', kwargs={self.pk_url_kwarg: project.pk})


class ProjectDeleteView(ProjectViewMixin, DeleteView):
    """User can delete the project only if he is a owner of project or superuser."""
    context_object_name = 'project'
    template_name = 'projects/delete.html'
    success_url = reverse_lazy('project_list')

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        project = cast(Project, self.object)  # pyright: ignore[reportAttributeAccessIssue]
        context = super().get_context_data(**kwargs)
        context['page_title'] = f'Delete project: {project.title}'
        return context

templates/projects/create.html
{% extends "template.html" %}
{% block content %}
    <h1>There you can create new project!</h1>
    {% include "projects/create_update_form_template.html" %}
{% endblock content %}

templates/projects/create_update_form_template.html
<form action="{{ form_action_url }}" method="post">
    {% csrf_token %}
    {% for field in form %}
        <div>
            {{ field.label }}
            {{ field }}
        </div>
        <hr />
    {% endfor %}
    <input type="submit" value="Save" />
    {% for field, errors in form.errors.items %}
        {% if field != "__all__" %}<p>{{ field }}:</p>{% endif %}
        <p>{{ errors }}</p>
    {% endfor %}
</form>

templates/projects/delete.html
{% extends "template.html" %}
{% block content %}
    <p>Are you sure you want to delete the project "{{ project.title }}"? This action is irreversible.</p>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Yes delete" />
    </form>
    <input type="button" value="Don`t delete" onclick="location.href='{% url "project_list" %}'" />
{% endblock content %}

templates/projects/detail.html
{% extends "template.html" %}
{% block content %}
    <p>Title: {{ project.title }}</p>
    <p>Owner: {{ project.owner.username }}</p>
    {% if project.members.all %}
        <p>Members:</p>
        <ul>
            {% for member in project.members.all %}<li>{{ member.username }}</li>{% endfor %}
        </ul>
    {% else %}
        <p>Members: No members.</p>
    {% endif %}
    <p>
        <a href="{% url "section_list" project_pk=project.pk %}">Sections:</a>
        {% if user_is_admin or user_is_project_owner %}
            <input type="button" value="+" onclick="location.href='{% url "section_create" project_pk=project.pk %} '" />
        {% endif %}
    </p>
    <ul>
        {% for section in project.sections.all %}
            <li>
                <a href="{% url "section_detail" project_pk=project.pk section_pk=section.pk %}">{{ section.name }}</a>
            </li>
        {% endfor %}
    </ul>
    {% if user_is_admin or user_is_project_owner %}
        <input type="button" value="edit" onclick="location.href='{% url "project_update" project_pk=project.pk %} '" />
        <input type="button" value="delete" onclick="location.href='{% url "project_delete" project_pk=project.pk %}'" />
    {% endif %}
{% endblock content %}

templates/projects/list.html
{% extends "template.html" %}
{% block content %}
    <p>
        My projects:
        <input type="button" value="+" onclick="location.href='{% url "project_create" %}'" />
    </p>
    <ul>
        {% for project in projects.my %}
            <li>
                <a href="{% url "project_detail" project_pk=project.pk %}">{{ project.title }}</a>
            </li>
        {% endfor %}
    </ul>
    <hr />
    <p>Member of projects:</p>
    <ul>
        {% for project in projects.member %}
            <li>
                <a href="{% url "project_detail" project_pk=project.pk %}">{{ project.title }}</a>
            </li>
        {% endfor %}
    </ul>
    {% if request.user.is_superuser %}
        <hr />
        <p>Admin list:</p>
        <ul>
            {% for project in projects.admin_list %}
                <li>
                    <a href="{% url "project_detail" project_pk=project.pk %}">{{ project.title }}</a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock content %}

templates/projects/update.html
{% extends "template.html" %}
{% block content %}
    <p>Change the data of project:</p>
    {% include "form_template.html" %}
{% endblock content %}